version: '3'
services:
  nginx:
   container_name: nginx-mtls
   image: nginx:1.20
   restart: always
   ports:
   - 8080:80
   volumes:
   - ./conf.d:/etc/nginx/conf.d

  app:
    restart: always
    image: springboot:1.20
    expose:
      - "8080"
    depends_on:
      - nginx
