{{- if .Values.dashboards.enabled }}
{{- $files := .Files }}
{{- range $path, $content := .Files.Glob "dashboards/*.json" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "grafana-dashboard-%s" (base $path | replace ".json" "" | trunc 63 | trimSuffix "-") | lower }}
  labels:
    grafana_dashboard: "true"
data:
  {{ base $path }}: |
{{ $content | indent 4 }}
---
{{- end }}
{{- end }}
